// <auto-generated />
namespace BankOfBIT_TP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedModule4Tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedModule4Tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202302100419136_addedModule4Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
