// <auto-generated />
namespace BankOfBIT_TP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class stored_procedures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stored_procedures));
        
        string IMigrationMetadata.Id
        {
            get { return "202302102253539_stored_procedures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
